### ISSUE TITLE
BlockingIOError: [Errno 35] write could not complete without blocking

### ISSUE THREAD

**Issue by jacebrowning** [nickstenning/honcho#168]
When running with a few processes on OS X 10.11.3 that write significant output, I occasionally see:

```
Traceback (most recent call last):
  File "/opt/boxen/pyenv/versions/3.5.0/bin/honcho", line 11, in <module>
    sys.exit(main())
  File "/opt/boxen/pyenv/versions/3.5.0/Python.framework/Versions/3.5/lib/python3.5/site-packages/honcho/command.py", line 266, in main
    COMMANDS[args.command](args)
  File "/opt/boxen/pyenv/versions/3.5.0/Python.framework/Versions/3.5/lib/python3.5/site-packages/honcho/command.py", line 213, in command_start
    manager.loop()
  File "/opt/boxen/pyenv/versions/3.5.0/Python.framework/Versions/3.5/lib/python3.5/site-packages/honcho/manager.py", line 106, in loop
    self._printer.write(msg)
  File "/opt/boxen/pyenv/versions/3.5.0/Python.framework/Versions/3.5/lib/python3.5/site-packages/honcho/printer.py", line 46, in write
    self.output.write(prefix + line + "\n")
BlockingIOError: [Errno 35] write could not complete without blocking
```

**Comment by nickstenning** [comment]
Thanks a lot for filing this issue! Are you able to provide a minimal test case that demonstrates this problem?

**Comment by jacebrowning** [comment]
I'm still working on that. It's occurring fairly regularly in my setup, but that's not a minimal test case.

A potentially related symptom is `honcho` stopping all terminal output midsteam while the child processes continue to run (as evidenced by other activity). Is there any way to get a verbose log every time `honcho` tries to write?

**Comment by nickstenning** [comment]
I'm going to close this issue. If you can still reproduce it (and especially if you have instructions on _how_ to reproduce it) please feel free to reopen.
