### ISSUE TITLE
Crash when printing to console with special characters.

### ISSUE THREAD

**Issue by TimotheeJeannin** [nickstenning/honcho#51]
I'm experiencing crashes when Honcho tries to print to console with special characters:

```
Traceback (most recent call last):
File "/app/.heroku/python/bin/honcho", line 9, in <module>
    load_entry_point('honcho==0.4.2', 'console_scripts', 'honcho')()
File "/app/.heroku/python/lib/python2.7/site-packages/honcho/command.py", line 292, in main
    app.parse()
File "/app/.heroku/python/lib/python2.7/site-packages/honcho/command.py", line 129, in parse
    options.func(self, options)
File "/app/.heroku/python/lib/python2.7/site-packages/honcho/command.py", line 190, in start
    sys.exit(process_manager.loop())
File "/app/.heroku/python/lib/python2.7/site-packages/honcho/process.py", line 114, in loop
File "/app/.heroku/python/lib/python2.7/site-packages/honcho/printer.py", line 22, in write
```

Here is a Stackoverflow question with more details:

http://stackoverflow.com/questions/19100116/looks-like-logs-are-crashing-my-django-app

**Comment by FGrosse** [comment]
Just in case anybody else runs into this: I had to export `PYTHONIOENCODING=utf-8` to solve the problem. Setting `LANG=en_US.UTF-8` didnt solve the problem on my zsh.
